modules = [
    './main',
    './other',
    '@rpgjs/default-gui',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/gamepad',
    '@rpgjs/chat',
    #'@rpgjs/title-screen'
]

assetsPath = '/game/assets'

[start]
    map = 'map'
    graphic = 'male'
    hitbox = [32, 32]

[titleScreen]
  mongodb = 'mongodb://localhost:27017/rpg'

[pwa]
  includeAssets = ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg']

[compilerOptions.build]
  pwaEnabled = false
