modules = [
    '@rpgjs/default-gui',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/gamepad',
    '@rpgjs/chat',
    '@rpgjs/title-screen',
    './main'
]

spritesheetDirectories = ['animations']

[start]
    map = 'map'
    graphic = 'male'

[titleScreen]
  mongodb = 'mongodb://localhost:27017/rpg'