name = 'My Game'
description = 'My first game with RPGJS'

modules = [
     './main',
    '@rpgjs/gamepad',
    '@rpgjs/default-gui'
]

[start]
    map = './main/maps/map'
    graphic = 'male'

[inputs]
    [inputs.action]
        repeat = true
        bind = 'up'