modules = [
    './main',
    '@rpgjs/default-gui',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/gamepad',
    '@rpgjs/chat'
]

spritesheetDirectories = ['animations']

[start]
    map = 'map'
    graphic = 'male'