name = 'My Game'
startMap = './main/maps/map'

modules = [
     './main',
    '@rpgjs/gamepad',
    '@rpgjs/default-gui'
]

[inputs]
    [inputs.action]
        repeat = true
        bind = 'down'

[titleScreen]
    mongoDb = 'mongodb://localhost:27017/test'
