modules = [
    './main',
    './other',
    '@rpgjs/default-gui',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/gamepad',
    '@rpgjs/chat',
   # '@rpgjs/title-screen'
]

[start]
    map = 'map'
    graphic = 'male'
    hitbox = [32, 32]

[titleScreen]
  mongodb = 'mongodb://localhost:27017/rpg'

  [inputs.up]
    name = "up"
    repeat = true
    bind = ["up", "h", "numpad 1"]
