[compilerOptions.build]
  pwaEnabled = false
  outputDir = 'browser'

[vite.build.lib]
    entry = "src/index.ts"
    name = "MyLib"
    fileName = "my-lib"

[vite.build.rollupOptions.output]
  format = "umd"